'use strict';
OAG.raw=v=>(v>=0?'+':'')+(v/100).toFixed(2);
OAG.weaponNum=(label,k,min=0,max=60000)=>OAG.num(label,'data-oag-weapon="'+k+'"',OAG.weapon[k],min,max);
OAG.weaponCheck=(label,k)=>'<label class="oag-check"><input type="checkbox" data-oag-weapon="'+k+'"'+(OAG.weapon[k]?' checked':'')+'>'+label+'</label>';
OAG.recoilCard=(label,k)=>'<div class="oag-quick"><h3>'+label+'</h3><output id="oag-value-'+k+'" class="oag-value">'+OAG.raw(OAG.weapon[k])+'</output><div id="oag-arrow-'+k+'" class="oag-small"></div><input type="range" min="-200" max="200" step="1" data-oag-weapon="'+k+'" value="'+OAG.weapon[k]+'" aria-label="'+label+'"><div class="oag-fine">'+[-10,-5,-1,1,5,10].map(v=>'<button data-oag-fine="'+k+':'+v+'">'+OAG.raw(v)+'</button>').join('')+'</div><div id="oag-saved-'+k+'" class="oag-compare">المحفوظ: '+OAG.raw(OAG.savedWeapon[k])+'</div></div>';
OAG.paintWeapon=()=>{
const w=OAG.weapon,advancedOpen=OAG.$('advanced')?.open||false;
OAG.$('weapon-content').innerHTML='<div class="oag-panel"><div class="oag-grid"><label>السلاح<select id="oag-weapon-slot"></select></label>'+OAG.weaponCheck('فعّل ضبط السلاح','enabled')+'<span class="oag-small">٢٤ سلاح مستقل لكل لعبة</span></div></div><div class="oag-recoil">'+OAG.recoilCard('التعويض العمودي','vertical')+OAG.recoilCard('التعويض الأفقي','horizontal')+'<div class="oag-quick"><h3>تهدئة اهتزاز التعويض</h3><input type="range" min="0" max="100" data-oag-weapon="antiShake" value="'+w.antiShake+'"><output id="oag-value-antiShake">'+w.antiShake+'%</output><p class="oag-small">يهدي التغييرات الصغيرة في التعويض المولّد.</p></div><div class="oag-quick"><h3>تنعيم التعويض</h3><input type="range" min="0" max="100" data-oag-weapon="smoothing" value="'+w.smoothing+'"><output id="oag-value-smoothing">'+w.smoothing+'%</output><p class="oag-small">خلّي الانتقال بين قيم التعويض أنعم.</p></div><div class="oag-quick"><h3>سرعة الرش وتوقيت التعويض</h3><div class="oag-grid">'+OAG.weaponNum('معدل السلاح — RPM','rpm',60,6000)+OAG.weaponNum('خطوة التعويض — ms','tickMs',1,1000)+'</div><p id="oag-shot"></p>'+OAG.weaponCheck('ظبّط توقيت التعويض على الـRPM','syncRpm')+'</div><div class="oag-quick"><h3>مدة إعادة التلقيم</h3>'+OAG.weaponNum('المدة — ms','reloadMs')+'<p class="oag-small">بتوقف التعويض بعد زر R أو مربع / X، وتستخدمها خطوة «استنى إعادة التلقيم».</p></div></div>'+OAG.renderAdvanced()+'<div class="oag-panel"><h3>بداية سريعة ونسخ الإعدادات</h3><div class="oag-line"><button data-oag-preset="reset">صفّر القيم</button><button data-oag-preset="smooth">بداية ناعمة</button><button data-oag-preset="direct">بداية مباشرة</button><select id="oag-copy-weapon"></select><button id="oag-copy-settings">انسخ من السلاح ده</button></div><p class="oag-small">البدايات دي للتجربة؛ ظبّط القوة بنفسك على سلاحك وحساسيتك.</p><p id="oag-compare-all"></p></div><div class="oag-footer"><button id="oag-save-weapon" class="oag-primary">احفظ إعدادات سلاح OAG</button><button id="oag-undo-weapon">ارجع خطوة</button><button id="oag-restore-weapon">ارجع للمحفوظ</button></div><p class="oag-small">الـRPM بيحسب فاصل الطلقات وتوقيت التعويض. مدة إعادة التلقيم ما بتقصّرش حركة السلاح جوّه اللعبة.</p>';
OAG.selectNames(OAG.$('weapon-slot'),OAG.weaponNames,'سلاح OAG');OAG.$('weapon-slot').value=OAG.state.weaponSlot;OAG.selectNames(OAG.$('copy-weapon'),OAG.weaponNames,'سلاح OAG');OAG.paintWeaponValues();OAG.bindWeaponButtons();OAG.$('advanced').open=advancedOpen};
OAG.paintWeaponValues=()=>{for(const k of ['vertical','horizontal']){OAG.$('value-'+k).textContent=OAG.raw(OAG.weapon[k]);OAG.$('arrow-'+k).textContent=OAG.weapon[k]===0?'مفيش تعويض':k==='vertical'?(OAG.weapon[k]>0?'↓ التعويض لتحت':'↑ التعويض لفوق'):(OAG.weapon[k]>0?'→ التعويض لليمين':'← التعويض للشمال')}for(const k of ['antiShake','smoothing'])OAG.$('value-'+k).textContent=OAG.weapon[k]+'%';OAG.$('shot').textContent='فاصل الطلقات: '+(60000/OAG.weapon.rpm).toFixed(2)+' ms';OAG.$('compare-all').textContent='الحالي: أفقي '+OAG.raw(OAG.weapon.horizontal)+' / عمودي '+OAG.raw(OAG.weapon.vertical)+' — المحفوظ: أفقي '+OAG.raw(OAG.savedWeapon.horizontal)+' / عمودي '+OAG.raw(OAG.savedWeapon.vertical)};
