'use strict';
OAG.loadCombo=async()=>{const s=OAG.state,g=s.game,n=s.slot;OAG.combo=OAG.comboFrom(await OAG.api('/api/oag/combo?game='+g+'&slot='+n));OAG.savedCombo=OAG.comboFrom(await OAG.api('/api/oag/combo?game='+g+'&slot='+n+'&saved=1'));OAG.comboState();OAG.paintCombo()};
OAG.checkBranch=b=>{const int=(v,min,max)=>Number.isInteger(v)&&v>=min&&v<=max;if(!b.then.length)throw Error('ضيف خطوة واحدة على الأقل في «نفّذ»');for(const c of b.conditions){if(!int(c.window,1,60000)||!int(c.hold,1,60000)||!int(c.threshold,-1000,1000)||!int(c.taps,1,20))throw Error('راجع مهلة الكشف والمسكة وحد التفعيل');if(!OAG.controls.some(x=>x.id===c.control))throw Error('اختار زر تشغيل معروف')}for(const [i,a] of [...b.then,...b.else].entries()){if((a.kind===7||a.kind===8)&&(a.first<(i<b.then.length?1:b.then.length+1)||a.first>i))throw Error('التكرار لازم يرجع لخطوة سابقة في نفس جزء الكومبو');for(const k of ['duration','before','after','interval'])if(!int(a[k],0,60000))throw Error('كل توقيت لازم يكون بين صفر و٦٠٠٠٠ ms');if(!int(a.count,0,100)||!int(a.x,-1000,1000)||!int(a.y,-1000,1000))throw Error('راجع عدد التكرارات وقوّة الحركة')}};
OAG.applyComboSnapshot=async(c,g,s)=>{if(new TextEncoder().encode(c.name).length>64)throw Error('اسم الكومبو طويل؛ قلله شوية');c.branches.forEach(OAG.checkBranch);const wire=c.branches.map(OAG.encodeBranch),token=Math.floor(Math.random()*0xfffffffe)+1;await OAG.post('/api/oag/combo-begin',{game:g,slot:s,token,name:c.name,enabled:c.enabled,mode:c.mode,cancelable:c.cancelable,branches:wire.length});for(let i=0;i<wire.length;i++)await OAG.post('/api/oag/combo-branch',{game:g,slot:s,token,branch:i,wire:wire[i]});await OAG.post('/api/oag/combo-apply',{game:g,slot:s,token});OAG.state.token=token;return token};
OAG.previewCombo=()=>{const c=OAG.clone(OAG.combo),g=OAG.state.game,s=OAG.state.slot;return OAG.serial(async()=>{await OAG.applyComboSnapshot(c,g,s);OAG.message(OAG.preview?'التعديل اتطبق في المعاينة، ولسه مش محفوظ':'التعديل اتطبق مؤقتًا على البيكو من غير حفظ')})};
OAG.saveCombo=async()=>{clearTimeout(OAG.comboTimer);const c=OAG.clone(OAG.combo),g=OAG.state.game,s=OAG.state.slot;await OAG.serial(async()=>{const token=await OAG.applyComboSnapshot(c,g,s);await OAG.post('/api/oag/combo-save',{game:g,slot:s,token})});if(g===OAG.state.game&&s===OAG.state.slot){OAG.savedCombo=c;OAG.comboState()}OAG.message(OAG.preview?'الكومبو اتحفظ داخل المعاينة':'كومبو OAG اتحفظ على البيكو')};
OAG.testCombo=async()=>{clearTimeout(OAG.comboTimer);await OAG.previewCombo();if(OAG.preview){OAG.message('معاينة الفرع الأول: '+OAG.combo.branches[0].then.map(a=>OAG.actionNames[a.kind]+(a.control?' '+OAG.controlName(a.control):'')).join(' ← '));return}await OAG.post('/api/oag/test',{game:OAG.state.game,slot:OAG.state.slot,branch:0});OAG.message('اختبار الكومبو بدأ؛ بيوقف تلقائيًا بعد ١٠ ثواني أو من زر الوقف')};
OAG.undoCombo=async()=>{clearTimeout(OAG.comboTimer);await OAG.serial(()=>OAG.post('/api/oag/discard-combo',{}));OAG.combo=OAG.clone(OAG.savedCombo);OAG.state.dirty=false;OAG.$('combo-state').textContent='محفوظ';OAG.$('combo-state').classList.remove('oag-dirty');OAG.paintCombo();OAG.message('رجعنا لآخر كومبو محفوظ')};
OAG.duplicateCombo=async()=>{const s=Number(prompt('عاوز تنسخ الكومبو لخانة كام؟ من ١ لـ١٦',Math.min(16,OAG.state.slot+1)));if(!s)return;if(!Number.isInteger(s)||s<1||s>16||s===OAG.state.slot)throw Error('اختار خانة تانية من ١ لـ١٦');clearTimeout(OAG.comboTimer);const c=OAG.clone(OAG.combo);await OAG.chain;OAG.savedCombo=OAG.comboFrom(await OAG.api('/api/oag/combo?game='+OAG.state.game+'&slot='+s+'&saved=1'));OAG.state.slot=s;OAG.$('slot').value=s;OAG.combo=c;OAG.changed(true);OAG.message('النسخة جاهزة في الخانة '+s+'؛ اضغط احفظ لو عايز تثبتها')};
