plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kareemabohussien.watertanksizer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kareemabohussien.watertanksizer'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '3.0.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
