#!/usr/bin/env python3
"""Embed the exact preview/UI assets; keep each response inside FIX2 TCP_SND_BUF."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/"tools/smart_ui"
OUTPUT=ROOT/"firmware/src/oag_smart_assets.h"
assets=sorted(ASSETS.glob("*"))
parts=["// Generated by oag/tools/embed_smart_ui.py. Edit tools/smart_ui instead.\n#pragma once\n"]
rows=[]
for i,p in enumerate(assets):
    if p.suffix not in (".js",".css",".html"): continue
    text=p.read_text()
    if ")OAGUI\"" in text: raise SystemExit("Raw delimiter collision")
    if len(text.encode())+640>=5840: raise SystemExit(f"{p.name}: response exceeds the pinned TCP budget")
    symbol=f"kOagSmartAsset{i}"
    parts.append(f'constexpr char {symbol}[] = R"OAGUI({text})OAGUI";\n')
    mime={".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".html":"text/html; charset=utf-8"}[p.suffix]
    rows.append(f'    {{"/{p.name}","{mime}",{symbol}}},')
parts.append("struct OagSmartAsset { const char* path; const char* mime; const char* body; };\n")
parts.append("constexpr OagSmartAsset kOagSmartAssets[] = {\n"+"\n".join(rows)+"\n};\n")
OUTPUT.write_text("".join(parts))
print("OAG_SMART_ASSETS=PASS")
