#!/usr/bin/env python3
"""Embed OAG UI as small independent assets within the frozen TCP buffer."""
from pathlib import Path
import argparse
root = Path(__file__).resolve().parents[1]
assets = root / 'tools/smart_ui_assets'
destination = root / 'firmware/src/smart_combo_assets.h'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
chunks = ['// Generated by oag/tools/embed_smart_ui.py; edit tools/smart_ui_assets.\n#pragma once\n']
items = []
for index, path in enumerate(sorted(assets.iterdir())):
    data = path.read_text(encoding='utf-8')
    if len(data.encode()) + 640 >= 5840:
        raise SystemExit(f'OAG asset exceeds frozen TCP_SND_BUF: {path.name}')
    if ')OAGSMART"' in data:
        raise SystemExit('Unexpected raw-string delimiter')
    symbol = 'kOagSmartHtml' if path.name == 'index.html' else f'kOagSmartAsset{index}'
    chunks.append(f'inline constexpr char {symbol}[] = R"OAGSMART({data})OAGSMART";\n')
    if path.name != 'index.html':
        mime = 'text/css' if path.suffix == '.css' else 'application/javascript'
        items.append(f'{{"/oag-smart/{path.name}", "{mime}; charset=utf-8", {symbol}}}')
chunks.append('struct OagSmartAsset { const char* path; const char* type; const char* bytes; };\n')
chunks.append('inline constexpr OagSmartAsset kOagSmartAssets[] = {\n' + ',\n'.join(items) + '\n};\n')
output = ''.join(chunks)
if args.check:
    if not destination.exists() or destination.read_text() != output:
        raise SystemExit('OAG smart UI generated header is stale')
else:
    destination.write_text(output, encoding='utf-8')
print(f'OAG_SMART_UI_ASSETS=PASS files={len(items)+1} max_bytes={max(p.stat().st_size for p in assets.iterdir())}')
