#!/usr/bin/env python3
"""Embed bounded portal assets; readable inputs remain under tools/pro_ui_assets."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
items=[('pro.html','kProHtml','HTML'),('pro.css','kProCss','CSS'),('pro-form.js','kProFormJs','JS'),('pro-monitor.js','kProMonitorJs','JS')]
out=['#pragma once\n// Generated by oag/tools/embed_pro_ui.py; edit tools/pro_ui_assets.\n']
for name,var,delimiter in items:
 text=(root/'tools/pro_ui_assets'/name).read_text()
 assert len(text.encode())+641<5840,(name,len(text.encode()))
 out.append(f'constexpr char {var}[] = R"{delimiter}({text}){delimiter}";\nstatic_assert(sizeof({var}) + 640u < TCP_SND_BUF);\n')
(root/'firmware/src/pro_input_portal_assets.h').write_text(''.join(out))
